INSERT INTO Airport VALUES ('YQH','CAN','Watson Lake','YT',' Unnamed Road','Watson Lake Airport','RGNL',1);
INSERT INTO Airport VALUES ('HKRE','KEN','Nairobi','Nairobi County',' ','Moi Air Base','RGNL',5);
INSERT INTO Airport VALUES ('JAV','GRL','Ilulissat','Qaasuitsup Kommune','B-1138 Mittarfimmut Aqqutaa','Ilulissat Airport','RGNL',4);
INSERT INTO Airport VALUES ('HKIS','KEN','Isiolo','',' Muriri-Miciimikuru Rd','Isiolo Airport','RGNL',2);
INSERT INTO Airport VALUES ('MSJ','JPN','Misawa','Aomori Prefecture',' ','Misawa Air Base','RGNL',4);
INSERT INTO Airport VALUES ('HOG','CUB','Holguin','Holguín',' CC','Frank Pais International Airport','INTL',5);
INSERT INTO Airport VALUES ('PPW','GBR','Papa Westray','Scotland',' ','Papa Westray Airport','RGNL',3);
INSERT INTO Airport VALUES ('RKP','USA','Rockport','TX','421 John D Wendell Rd','Aransas County Airport','RGNL',3);
INSERT INTO Airport VALUES ('CCH','CHL','Chile Chico','Región de Aysén del General Carlos Ibáñez del Campo',' X-753','Chile Chico Airport','RGNL',5);
INSERT INTO Airport VALUES ('WSP','NIC','Waspam','RAAN',' NN-73','Waspam Airport','RGNL',3);
INSERT INTO Airport VALUES ('ZJG','CAN','Jenpeg','MB',' ','Jenpeg Airport','RGNL',4);
INSERT INTO Airport VALUES ('DKR','SEN','Dakar','Dakar',' Unnamed Road','Léopold Sédar Senghor International Airport','INTL',2);
INSERT INTO Airport VALUES ('KTD','JPN','Kitadaito','Okinawa Prefecture',' ','Kitadaito Airport','RGNL',5);
INSERT INTO Airport VALUES ('UUS','RUS','Yuzhno-sakhalinsk','',' ','Yuzhno-Sakhalinsk Airport','RGNL',5);
INSERT INTO Airport VALUES ('BUX','COD','Bunia','Province orientale',' ','Bunia Airport','RGNL',3);
INSERT INTO Airport VALUES ('SAK','ISL','Saudarkrokur','',' ','Sauðárkrókur Airport','RGNL',2);
INSERT INTO Airport VALUES ('WSAT','SGP','Tengah','',' Unnamed Road','Tengah Air Base','RGNL',5);
INSERT INTO Airport VALUES ('EDMN','DEU','Mindelheim','BY','9 Lettenbachstraße','Mindelheim-Mattsies Airport','RGNL',3);
INSERT INTO Airport VALUES ('QNV','BRA','Nova Iguacu','RJ',' R. Savério José Bruno','Aeroclube Airport','RGNL',5);
INSERT INTO Airport VALUES ('BXU','PHL','Butuan','',' ','Bancasi Airport','RGNL',2);
INSERT INTO Airport VALUES ('YSP','CAN','Marathon','ON',' ON-17','Marathon Airport','RGNL',2);
INSERT INTO Airport VALUES ('RZR','IRN','Ramsar','Mazandaran Province',' ','Ramsar Airport','RGNL',2);
INSERT INTO Airport VALUES ('OIBS','IRN','Siri Island','',' خیابان ایران','Sirri Island Airport','RGNL',5);
INSERT INTO Airport VALUES ('HYS','USA','Hays','KS','13-3950 E 8th St','Hays Regional Airport','RGNL',3);
INSERT INTO Airport VALUES ('ZPH','USA','Zephyrhills','FL',' ','Zephyrhills Municipal Airport','RGNL',2);
INSERT INTO Airport VALUES ('PBI','USA','West Palm Beach','FL','3200 Belvedere Rd','Palm Beach International Airport','INTL',1);
INSERT INTO Airport VALUES ('GCC','USA','Gillette','WY','2000 Airport Rd','Gillette Campbell County Airport','RGNL',5);
INSERT INTO Airport VALUES ('HIR','SLB','Honiara','Guadalcanal Province',' Kukum Hwy','Honiara International Airport','INTL',4);
INSERT INTO Airport VALUES ('POX','FRA','Pontoise','Île-de-France',' L Aérodrome','Pontoise - Cormeilles-en-Vexin Airport','RGNL',4);
INSERT INTO Airport VALUES ('PBF','USA','Pine Bluff','AR',' ','Grider Field','RGNL',5);
INSERT INTO Airport VALUES ('HEI','DEU','Büsum','SH','7 Am Flugpl.','Heide-Büsum Airport','RGNL',4);
INSERT INTO Airport VALUES ('EBWE','BEL','Weelde','Vlaanderen',' ','Weelde Air Base','RGNL',3);
INSERT INTO Airport VALUES ('VYMY','MMR','Monywa','Sagaing Region',' Unnamed Road','Monywar Airport','RGNL',2);
INSERT INTO Airport VALUES ('TGZ','MEX','Tuxtla Gutierrez','Chis.',' Francisco Sarabia','Angel Albino Corzo International Airport','INTL',2);
INSERT INTO Airport VALUES ('OMN','USA','Ormond Beach','FL','770 Airport Rd','Ormond Beach Municipal Airport','RGNL',1);
INSERT INTO Airport VALUES ('SVJ','NOR','Svolvær','',' ','Svolvær Helle Airport','RGNL',1);
INSERT INTO Airport VALUES ('HIB','USA','Hibbing','MN','11038 MN-37','Range Regional Airport','RGNL',5);
INSERT INTO Airport VALUES ('SLP','MEX','San Luis Potosi','S.L.P.',' Carr. a Matehuala Km 9.5','Ponciano Arriaga International Airport','INTL',5);
INSERT INTO Airport VALUES ('MMT','USA','Eastover','SC',' ','Mc Entire Joint National Guard Base','RGNL',4);
INSERT INTO Airport VALUES ('CKS','BRA','Parauapebas','PA',' ','Carajás Airport','RGNL',3);
INSERT INTO Airport VALUES ('CRA','ROU','Craiova','DJ','325 Calea București','Craiova Airport','RGNL',1);
INSERT INTO Airport VALUES ('GDE','ETH','Gode','Somali',' ','Gode Airport','RGNL',3);
INSERT INTO Airport VALUES ('ANE','FRA','Angers/Marcé','Pays de la Loire',' ','Angers-Loire Airport','RGNL',4);
INSERT INTO Airport VALUES ('YAB','CAN','Arctic Bay','NU',' ','Old Arctic Bay Airport','RGNL',2);
INSERT INTO Airport VALUES ('SOQ','IDN','Sorong','Papua Bar.',' Unnamed Road','Dominique Edward Osok Airport','RGNL',4);
INSERT INTO Airport VALUES ('SBZ','ROU','Sibiu','SB','73 Șoseaua Alba Iulia','Sibiu International Airport','INTL',1);
INSERT INTO Airport VALUES ('VXC','MOZ','Lichinga','Niassa Province',' ','Lichinga Airport','RGNL',5);
INSERT INTO Airport VALUES ('HSAW','SSD','Aweil','Northern Bahr el Ghazal',' Station Way','Aweil Airport','RGNL',4);
INSERT INTO Airport VALUES ('EOI','GBR','Eday','Scotland',' ','Eday Airport','RGNL',3);
INSERT INTO Airport VALUES ('AEA','KIR','Abemama','Gilbert Islands',' ','Abemama Atoll Airport','RGNL',1);
INSERT INTO Airport VALUES ('UHPO','RUS','Kozyrevsk','Kamchatka Krai',' ','Kozyrevsk Airport','RGNL',5);
INSERT INTO Airport VALUES ('LIBA','ITA','Amendola','Apulia',' ','Amendola Air Base','RGNL',3);
INSERT INTO Airport VALUES ('LOGG','AUT','Punitz-Guessing','Burgenland','201 Punitz','Flugplatz Punitz','RGNL',1);
INSERT INTO Airport VALUES ('BQT','BLR','Brest','Brest Region',' Unnamed Road','Brest Airport','RGNL',3);
INSERT INTO Airport VALUES ('BKO','MLI','Bamako','Bamako Capital District',' ','Senou Airport','RGNL',5);
INSERT INTO Airport VALUES ('PMG','BRA','Ponta Pora','MS','131 R. Livorno','Ponta Porã Airport','RGNL',4);
INSERT INTO Airport VALUES ('CHM','PER','Chimbote','Áncash',' Via Aeropuerto Tte. FAP Jaime Montreuil M.','Teniente FAP Jaime A De Montreuil Morales Airport','RGNL',5);
INSERT INTO Airport VALUES ('YKS','RUS','Yakutsk','Sakha Republic',' ','Yakutsk Airport','RGNL',2);
INSERT INTO Airport VALUES ('JHW','USA','Jamestown','NY','3163 Airport Dr','Chautauqua County-Jamestown Airport','RGNL',4);
INSERT INTO Airport VALUES ('RNT','USA','Renton','WA','616 Perimeter Rd W','Renton Municipal Airport','RGNL',3);
